server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/iers_contacts_db
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  application:
    name: contacts-service

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

logging:
  level:
    com.Contact: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

springdoc:
  swagger-ui:
    config-url: /auth/v3/api-docs/swagger-config
    url: /auth/v3/api-docs
    disable-swagger-default-url: true