server:
  port: 8081
  forward-headers-strategy: framework
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/iers_contacts_db
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  application:
    name: contacts-service
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
      allowed-headers: "*"
      max-age: 3600

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

logging:
  level:
    com.Contact: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    url: /contacts/v3/api-docs
    config-url: /contacts/v3/api-docs/swagger-config