server:
  port: 8081
  forward-headers-strategy: framework
  servlet:
    context-path: /
  compression:
    enabled: true
    min-response-size: 1024
  http2:
    enabled: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/iers_contacts_db
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  application:
    name: contacts-service

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

logging:
  level:
    com.Contact: INFO
    org.springframework.web.cors: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    url: /contacts/v3/api-docs
    config-url: /contacts/v3/api-docs/swagger-config
    use-root-path: true

